[FIX] Fixed menu looks buggy when scrolling (Podio bug_25)
t3kit/felayout_t3kit pull request #26
Opened 2016-10-04 17:05 UTC by vhusaruk92

2016-12-01 10:33 UTC, dmh requested changes

2016-12-01 10:33 UTC, dmh commented on dev/js/main/header/header.js
> +        console.log("vika");
?

2016-12-01 10:33 UTC, dmh commented on dev/js/main/header/header.js
> +        $(window).on('resize',function() {
we should try to fix it without resize event if it possible?

2016-12-04 15:34 UTC, vhusaruk92 commented on dev/js/main/header/header.js
> +        $(window).on('resize',function() {
please, check new commit

2016-12-23 13:37 UTC, pxamike commented
My pull-request ( https://github.com/t3kit/felayout_t3kit/pull/52 ) should be the proper fix for this issue, so I would not merge this. (However my solution is inspired by this, so cheers to vhusaruk92!)

2016-12-23 13:37 UTC, closed without merging