[FEATURE] add new grid element 'slider container'
t3kit/felayout_t3kit pull request #38
Opened 2016-11-22 17:01 UTC by vhusaruk92

Grid element “swiper-container” for almost all of content elements (bigIconTextButton, iconTextLink, Images, TextAndMedia, ImageTextLink, quotes, Text&Media).

With settings: 
checkboxes: 1)button  2) pagination 3)loop;
selection:1) autoplay 2)effects 3)slidesPerView 4)speed.

2016-12-01 10:26 UTC, dmh requested changes

2016-12-01 10:26 UTC, dmh commented on dev/js/main/contentElements/sliderContainer.js
> +                slider.slideTo(focusIndex);
no need to call this function twice

2016-12-04 11:28 UTC, vhusaruk92 commented on dev/js/main/contentElements/sliderContainer.js
> +                slider.slideTo(focusIndex);
+

2016-12-04 11:28 UTC, vhusaruk92 commented on dev/js/main/contentElements/sliderContainer.js
> +                slider.slideTo(focusIndex);
thank you, have done!

2016-12-06 10:37 UTC, merged